name: Deploy PR Preview

on:
  workflow_run:
    workflows: ["Build PR Preview"]
    types: [completed]

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Class Diagram artifact
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: class-diagram-html
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: . # Download to the root of the workspace
      - name: Store PR id as variable
        id: pr
        run: |
          echo "id=$(<pr-id.txt)" >> $GITHUB_OUTPUT
          rm -f pr-id.txt

      - name: Define Surge Domain
        id: surge_domain
        run: |
          PR_NUMBER=${{ steps.pr.outputs.id }}
          SURGE_DOMAIN="pr-$PR_NUMBER-.project-graph-generator-preview.surge.sh"
          echo "SURGE_DOMAIN=$SURGE_DOMAIN" >> $GITHUB_OUTPUT

      - name: Deploy to Surge
        run: npx surge ./ https://${{ steps.surge_domain.outputs.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      - name: Update PR status comment on success
        uses: quarkusio/action-helpers@main
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.id }}
          body: |
            🚀 PR Preview for **blog** ${{ github.sha }} has been successfully built!
            * https://${{ steps.surge_domain.outputs.SURGE_DOMAIN }}
          body-marker: <!-- Preview status comment marker -->
      - name: Update PR status comment on failure
        uses: quarkusio/action-helpers@main
        if: ${{ failure() }}
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.id }}
          body: |
            😭 Deploy PR Preview failed.
          body-marker: <!-- Preview status comment marker -->
